### ISSUE TITLE
"Windows cannot find '**undefined**/main.pdz"

### ISSUE THREAD

**Issue by ZeAntwan** [orta/vscode-playdate#12] opened 2022-04-06 20:36 UTC
Using the 0.0.5 version of the extension, I get an error after running the debug command:
`"Windows cannot find 'undefined/main.pdz"`

But the simulator still launches afterwards, and working as intended

My project is based on this template https://github.com/Whitebrim/VSCode-PlaydateTemplate with no edits to any of the json files under .vscode.

This is not a critical issue, but took me sometime to narrow the issue to the extension and not my machine!

Thanks for the great plugin, and let me know if more details or files are needed!

**Comment by bombsimon** [comment] 2022-04-07 05:49
This is not  something that comes from this plugin.

@ZeAntwan If you have not edited any json files in `.vscode` it means that you're not using this plugin. The project you're linking too comes with a bunch of [tasks](https://github.com/Whitebrim/VSCode-PlaydateTemplate/blob/master/.vscode/tasks.json) to build the app and a separate [launch](https://github.com/Whitebrim/VSCode-PlaydateTemplate/blob/master/.vscode/launch.json) setting. I went ahead and cloned the repository and I can reproduce this so I would suggest to file an issue there.

If you want to use this plugin, have a look at the [README](https://github.com/orta/vscode-playdate#getting-set-up) in this repository. This is what I'm using which is working on Windows.

**`launch.json`**

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "type": "playdate",
      "name": "Run app in Playdate simulator",
      "preLaunchTask": "Compile App",
      "source": "${workspaceFolder}/Source",
      "output": "${workspaceFolder}/Output.pdx",
    }
  ]
}

```

**`tasks.json`**

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Compile App",
      "command": "pdc",
      "args": [
        "Source",
        "Output.pdx"
      ],
      "type": "shell"
    }
  ]
}
```

However, now that I saw the settings in your linked repository I realize we should probably open the simulator the sme way in this plugin (`%PLAYDATE_SDK_PATH%/bin/bin/PlaydateSimulator.ex path\to\Output.pdx`). I'll try to file a PR for this.

**Comment by bombsimon** [comment] 2022-04-07 14:57
> And then the simulator doesn't launch (might just have to select the simulator in this prompt, but just want to make sure I'm getting stuff right)

Yes, that is correct. On macOS, the Simulator is automatically assigned with the `pbx` extention but the `pdz` is not for Windows. So for now, set the simulator to be associated with `pdz` files and it should work.

Long term I think we should use the environment variable and point to the simulator binary, I'll try to get to that as soon as possible!

**Comment by ZeAntwan** [comment] 2022-04-07 18:46
Got it! Thanks for the help! And sorry, I am very new in using the VS Code debug flow and all.
The solution you provided helped! I can make it work on a machine with the SDK on the "normal" location (C drive), but on my desktop machine, when the simulator starts it asks for the SDK, so maybe the fix you're suggesting will help in that regard?

**Comment by bombsimon** [comment] 2022-04-23 18:36
@ZeAntwan The plugin no tries to open the simulator if `source` and `output` is not configured. This is because if `output` is missing it won't successfully compile and bail out.

I also added an issue in the [Whitebrim/VSCode-PlaydateTemplate](https://github.com/Whitebrim/VSCode-PlaydateTemplate) repository with a suggestion to avoid confusion between the template using its own compiling and launching and this plugin.

Is this sorted enough for you so I can close this issue?

**Comment by ZeAntwan** [comment] 2022-04-23 21:48
Hi! And thanks for looking into this!

In a way, the update didn't change my alternative workflow much... I still have this Missing SDK issue when running the new command or F5 for debug, but I think this is an issue that has already been reported on Playdate Dev forum (my SDK is not on the C drive...).
And also, If I were to use the plugin only, I seem to have lost the ability to specify where to build and the file name.

So, I think I'm still having the same issue. PDZ file is created and working, but simulator doesn't find the SDK for some reason, and I don't understand why the template task works, and not the plugin. BUT it might not be a plugin issue anymore? And if so, sure you can close the issue 😊

**Closed** 2022-04-23 22:02 UTC

**Comment by bombsimon** [comment] 2022-04-24 14:28
It sounds like you sorted it out but to clarify and for others if they land here:

You can (and have to) specify both `source` and `output` if you're running the debugger with F5. This should work independent on where you put the SDK as long as you set the environment variable `PLAYDATE_SDK_PATH` before launching VS Code _or_ by setting the full path (including the drive) in the launch settings. F.ex.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "type": "playdate",
      "name": "Run app in Playdate simulator",
      "source": "${workspaceRoot}/Source",     // This has to be where your source code is
      "output": "${workspaceRoot}/Output.pdx", // This can be wherever you want
      "sdkPath": "D:\\dev\\PlaydateSDK"
    }
  ]
}
```
